### ISSUE TITLE
Diode marker distinction missing in build guide

### ISSUE THREAD

**Issue by dabell-cc** [ClicketySplit/build-guides#1]
While it's typical that the cathode is marked on the diode package the current build guide does assume that knowledge and only refers to the correct polarity as "same direction as the shield’s diode direction".
Adding this info, and perhaps a quick reference to using a DMM with diode function to double-check the polarity, would make the build more accessible to those with less hardware background.

**Comment by ClicketySplit** [comment]
Added a note to the documentation with regards to the white/grey line on the diode itself.

Thank you, @dabell-cc!
