### ISSUE TITLE
Consider safety in tools and materials

### ISSUE THREAD

**Issue by dabell-cc** [ClicketySplit/build-guides#2]
While soldering by eye it's not a bad idea to wear safety glasses - consider adding them to the tools and materials list.
In regards to safety, recommending a fume extractor or at the very least a 'well ventilated area' is a good idea.

**Comment by ClicketySplit** [comment]
Thanks @dabell-cc!

I'll move the Safety Equipment above the Tools and Materials section and add a paragraph about setting up a clean workspace.

**Comment by ClicketySplit** [comment]
Updated documentation.  Thank you, @dabell-cc.
